---
resources:
  - name: cf-flask-skeleton
    type: git
    source:
      uri: git@github.com:mattclarkdotnet/cf-flask-skeleton.git
      branch: master
      private_key: {{cf-flask-skeleton-github-private-key}}
  - name: version
    type: semver
    source:
      bucket: cf-flask-skeleton-pipeline-artifacts
      key: current-version
      access_key_id: {{s3-access-key-id}}
      secret_access_key: {{s3-secret-access-key}}
      initial_version: 1.0.0
jobs:
  - name: unit
    plan:
    - get: cf-flask-skeleton
      trigger: true
    - task: unit
      file: cf-flask-skeleton/ci/unit.yml